### ISSUE TITLE
add possibility to install own theme

### ISSUE THREAD

**Issue by russ666** [johnpbloch/wordpress-core#10]
now it could be handled by composer hooks, but it looks ugly.
```
    "scripts": {
        "pre-install-cmd": [
            "mv wordpress/wp-content/themes/custom-theme temp-custom-theme"
        ],
        "post-install-cmd": [
            "mv temp-custom-theme wordpress/wp-content/themes/custom-theme"
        ],
        "pre-update-cmd": [
            "mv wordpress/wp-content/themes/custom-theme temp-custom-theme"
        ],
        "post-update-cmd": [
            "mv temp-custom-theme wordpress/wp-content/themes/custom-theme"
        ]
    }
```

**Comment by johnpbloch** [comment]
Thanks for stopping by and opening an issue. This package doesn't support nesting any custom code inside it. Typically, what you would do to use custom themes and plugins if you want to use composer to manage both core and the theme, etc. is move the wp-content directory out of core [using the provided constants](https://codex.wordpress.org/Determining_Plugin_and_Content_Directories#Constants). Then you can use composer to manage theme and plugin dependencies.
