### ISSUE TITLE
Why there is no .htaccess file?

### ISSUE THREAD

**Issue by AlmogBaku** [johnpbloch/wordpress-core#12]
Why there is no `.htaccess` file for the distribution version?

**Comment by AlmogBaku** [comment]
If I'm not mistaken, the release version(zip file) does include it.
It could be great if somehow you can force the bot to add it, since the composer override this file everytime(and post-script is nasty)

**Comment by johnpbloch** [comment]
:facepalm: looks like next time I need to verify the account it'll post to if I reply by email... Terribly sorry about any confusion from my accidentally replying from my bot account.
