### ISSUE TITLE
master branch isn't updated since Dec 2019

### ISSUE THREAD

**Issue by ocean90** [johnpbloch/wordpress-core#25]
It looks like updating master branch is broken. The last commit 8549401dd9cbdc1ff0b9c7e266d117d89bd6d832 was on 15 Dec 2019.

https://github.com/johnpbloch/wordpress-core/commits/master

**Comment by johnpbloch** [comment]
Thanks for letting me know! The problem has been fixed and it should update as expected in the future. I'll be keeping an eye on it for the next few days, though.
