### ISSUE TITLE
Missing themes ?

### ISSUE THREAD

**Issue by fmarquis** [johnpbloch/wordpress-core#28]
Hi @johnpbloch,

I'm using your project to manage a simple Wordpress with Composer and I just found a strange thing : 
My installation seems to have only the last 3 official themes, instead of the 11 ones from the official repo
 
If you look at the 5.6 branch, you can see all the themes : 
https://github.com/johnpbloch/wordpress-core/tree/5.6/wp-content/themes
but if you look at the 5.6.0 tag, there is only the 3 latest ones : 
https://github.com/johnpbloch/wordpress-core/tree/5.6.0/wp-content/themes

Is there a reason for this ?
I will now require my missing  "wpackagist-theme/twentyseventeen", but I would like to understand why all the default themes are not provided with your repo.
Thanks in advance

**Comment by johnpbloch** [comment]
Hi @fmarquis, thanks for stopping by. Tagged releases are built from the release downloads on wordpress.org, so whatever themes ship with that copy of core are what's in my package. I suppose I could have tweaked the themes in the package after download, but to be frank, if I were to do that it would most likely be in the opposite direction of removing all plugins and themes. Hope that answers your question!

**Comment by fmarquis** [comment]
Hi, thanks for your reply

The strange things is that on Worpress releases, all themes are here : https://github.com/WordPress/WordPress/tree/5.6/wp-content/themes
We can logically see them also in your 5.6 branch : https://github.com/johnpbloch/wordpress-core/tree/5.6/wp-content/themes
But if we look into the 5.6.0 tag, only the latest 3 themes are remaining : https://github.com/johnpbloch/wordpress-core/tree/5.6.0/wp-content/themes
I looked into your build project (https://github.com/johnpbloch/build-wp), but didn't find anything that could explain this cleanup

My initial install was basic, so I directly used the latest theme shipped with your release (twentyseventeen at the time), and now this theme is no more shipped, which cause problem of course.
I just wanted to prevent someone else from doing the same mistake ;)

So the "right" way to use it would be : 
* require "johnpbloch/wordpress"
* adjust configuration to use another "wp-content" than the one shipped
* require the themes/plugins you want to use (they should go into your specific "wp-content", thanks to dropin-paths configuration)

Or I still miss something ?

**Comment by johnpbloch** [comment]
I'm sorry about inadvertently causing your theme to disappear and all the frustration and extra work it no doubt caused. 😩 I'm glad to hear you found the solution and got your site back up and running.

To clarify, although the release on GitHub has the themes, the zip distributed by core doesn't (e.g. https://wordpress.org/latest.zip). It's the latter archive that I'm using.

There are other ways that this package could be used and configured, such as using composer to create a new project with this package as the base, keep wp-content in its normal place, and only use composer to manage plugins and themes. That being said, the configuration you described is the recommended one.

**Comment by fmarquis** [comment]
Hey, don't worry, it's the life of a developer ! This was detected before going into production, so no harm done

Your project has brought me more gains than problems so far ;)

I will adapt my project to theses recommendations, thanks again for your help and your work !
