### ISSUE TITLE
Out of date assets

### ISSUE THREAD

**Issue by tillkruss** [johnpbloch/wordpress-core#3]
Some of the compress JavaScript assets in this repo are slightly different from the originals.

That causes security scanners like [VaultPress](https://vaultpress.com/) to recognize them as a security thread.

The differences are minimal, but should be resolved.

`wp-emoji.min.js` from this repo:
https://raw.githubusercontent.com/johnpbloch/wordpress-core/master/wp-includes/js/wp-emoji.min.js

WordPress SVN:
https://core.svn.wordpress.org/tags/4.7.4/wp-includes/js/wp-emoji.min.js

WordPress Git:
https://github.com/WordPress/WordPress/blob/4.7.4/wp-includes/js/wp-emoji.min.js

**Comment by swissspidy** [comment]
For anyone wondering, this has been fixed a while ago.

See https://github.com/johnpbloch/wordpress/issues/32 and https://github.com/johnpbloch/wordpress/issues/33.
