### ISSUE TITLE
No update for the latest version (WordPress 6.3)

### ISSUE THREAD

**Issue by mathias-heilmann** [johnpbloch/wordpress-core#32]
The latest 6.3 [release of wordpress](https://de.wordpress.org/download/releases/) was made two days ago. How is this repository kept up to date? I suspect this @johnpbloch-bot does, but is he/she/it on holiday?

**Comment by johnpbloch** [comment]
Thanks for opening this issue and thank you for your patience. It turns out GitHub very helpfully disabled the GH Action that updates the two repositories and I must have missed the notification, if one was ever sent. The builds should be resuming shortly.

**Comment by mathias-heilmann** [comment]
Thank you so much!
