### ISSUE TITLE
Too low PHP min version in 6.6

### ISSUE THREAD

**Issue by szepeviktor** [johnpbloch/wordpress-core#35]
https://github.com/johnpbloch/wordpress-core/blob/3c8068623544eebbe45786dc20221c3cfed7a683/composer.json#L26

@johnpbloch Now 6.6 branch differs from WordPress core.

**Comment by johnpbloch** [comment]
Thanks for letting me know. I'll update the build script later today.

**Comment by szepeviktor** [comment]
Glad to contribute.

**Comment by johnpbloch** [comment]
It appears the upstream repository prematurely created their 6.6 branch and then deleted it. Whenever they recreate the 6.6 branch, this will resolve itself.

**Comment by johnpbloch** [comment]
I went ahead and copied a snapshot of `master` into the 6.6 branch in this repo and updated the PHP version. It's essentially the same thing as master anyway, but this way anybody who mistakenly tries to install 6.6 before its release will at least get some code, even if it is out of date for a while.

**Comment by szepeviktor** [comment]
Thank you.
