### ISSUE TITLE
WordPress 6.7 is missing

### ISSUE THREAD

**Issue by Soean** [johnpbloch/wordpress-core#37]
WordPress 6.7 was released yesterday, the tag is missing.
It looks like the sync ran for the last time on 18 October.

**Comment by Soean** [comment]
Is there any way we can automatically check that the sync is working? If a security update is released now, this would cause problems.

Of course there are alternatives such as the package from roots, but we are actually very satisfied with this package. 

@johnpbloch Can we support you in any way?

**Comment by archon810** [comment]
Thanks for the mention of roots. I just looked it up, it looks like a drop-in replacement.

https://roots.io/updates-to-roots-wordpress-composer-package/

I don't want to switch either, so I'm waiting for @johnpbloch too for now, but I'm happy there's an alternative if we need it.

**Comment by johnpbloch** [comment]
Updates should resume shortly. This was a case of unintended side-effects of tightening down some security settings in the bot account.

**Comment by Soean** [comment]
Nice, thank you 👍
